### ISSUE TITLE
SVGs aren't displayed in 1.2.1 release in Android Studio on design tab

### ISSUE THREAD

**Issue by carlos-mg89** [BigBadaboom/androidsvg#140]
Hi,

I've been following the documentation and some issues in the repository and have finally been able to include SVGImageView in my layout.xml files. However, the SVGs aren't displayed as PNGs are with ImageButton or ImageView components in the design tab of the layout XML files. Would it be difficult for the design tab to render the PNGs of the SVGImageView components?

Just to be really clear, the SVGs are displayed while running the app. However, they aren't displayed while in Android Studio, in the design tab of the layout XML files.

Thanks for this awesome project! It definitely helps to get rid of the multiple PNGs in the different screen sizes.

**Comment by carlos-mg89** [comment]
It's not ideal, but I have figured out a way of doing so by adding a PNG to the src attribute. Example:

```
<com.caverock.androidsvg.SVGImageView
            android:id="@+id/routingPlanningFragmentOptions"
            android:layout_width="24dp"
            android:layout_height="24dp"
            android:src="@drawable/action_more_white"
            svgimageview:svg="action_more_white.svg" />
```

This way I need the SVG and the PNG. But the SVGImageView is displayed in the design tab and then in the app while on runtime.

I was checking the design log and found the following:

```
android.content.res.Resources$NotFoundException: Could not find null resource matching value 0x7FFF0001 (resolved name: svg) in current configuration.
	at android.content.res.Resources_Delegate.throwException(Resources_Delegate.java:1076)
	at android.content.res.Resources_Delegate.throwException(Resources_Delegate.java:1063)
	at android.content.res.Resources_Delegate.openRawResource(Resources_Delegate.java:952)
	at android.content.res.Resources.openRawResource(Resources.java:1209)
	at com.caverock.androidsvg.SVG.getFromResource(SVG.java:187)
	at com.caverock.androidsvg.SVG.getFromResource(SVG.java:172)
	at com.caverock.androidsvg.SVGImageView.setImageResource(SVGImageView.java:128)
	at com.caverock.androidsvg.SVGImageView.init(SVGImageView.java:85)
	at com.caverock.androidsvg.SVGImageView.<init>(SVGImageView.java:66)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:481)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:264)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:222)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:209)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:337)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:348)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:248)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:863)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:837)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:866)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:837)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:394)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:325)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:384)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:193)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:544)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$3(RenderTask.java:678)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I believe this is the reason why the SVG doesn't get displayed on the design tab. Probably it doesn't find a way of loading the asset while there, however it definitely finds the way of doing that on runtime.

**Comment by BigBadaboom** [comment]
I agree that it would be nice to be able to display the SVG - or at least some sort of stand-in image like ImageView does.  Unfortunately, I don't believe Android Studio has any mechanism that would allow me to do that.

**Comment by BigBadaboom** [comment]
I agree that it would be nice to display a preview of the SVG, or at least a placeholder image like ImageView does. Unfortunately,, as far as I know, Android Studio has no mechanism for doing that.

When I get a chance, I will check out the error you are seeing though. It definitely shouldn't be doing that.

**Comment by carlos-mg89** [comment]
What do you think about the seconds answer I gave you?

I was able to get a preview in the design tab by adding a PNG file. This is far from ideal, since I will have to download / generate an SVG and a PNG to get that preview.

Perhaps there could be an automated way of exporting the SVG to PNG and get that preview¿? Since it gets displayed when adding a PNG in the src attribute.

I will continue to add both the SVG and a PNG so I get that preview over there. It's useful if you want to get rid of having the different PNGs for each screen size. But it's definitely important to me to see the preview.

**Comment by BigBadaboom** [comment]
If it is important to you to see the image at design time, then that seems like a reasonable solution.  You could probably make a gradle rule to remove or exclude the PNGs when you build your release version.

Also Android Studio can create the PNGs for you.  So you don't need to generate them yourself.

**Comment by carlos-mg89** [comment]
@BigBadaboom would you be able to point me any document / reference where I could check on how to make Android Studio generate for me the PNGs based on an SVG file? I think that would be perfect.

**Comment by BigBadaboom** [comment]
https://developer.android.com/studio/write/vector-asset-studio

If you minimum SDK version is less than 21, AndroidStudio will generate PNGs automatically so that devices that don't support VectorDrawable will still work.

You may be using the support library to enable VectorDrawable support on older versions of Android, I'm not sure what effect including that has (if any) on PNG generation.  You may need to experiment a little.

**Comment by carlos-mg89** [comment]
@BigBadaboom I've just checked the Vector Asset Studio, and it actually works pretty nicely. Even under API 21. So now I can just add one SVG and get them printed on screen in the design mode.

One question, just to clarify and make sure I have understood things right. If with the Vector Asset Studio I can add SVG files into my project to use them in ImageViews, ImageButtons, etc, what's the real benefit of SVGImageView? Since the VectorDrawable is supported by Google, works out of the box if your API is version 21 or higher, and just requires the Support Library (which many people will be using anyway, as I did) and that even allows a min SDK version of 7.

Is it because SVGImageView support many more SVG functionalities than the ones allowed to be used in the VectorDrawables? Now I'm just quoting the description of your library:

> AndroidSVG is a SVG parser and renderer for Android. It has almost complete support for the static visual elements of the SVG 1.1 and SVG 1.2 Tiny specifications (except for filters).

Thanks in advance for all your support. You have been tremendously useful so far.

**Comment by BigBadaboom** [comment]
VectorDrawables are basically a very limited subset of SVG.  They are great for simple icons, and if all your SVGs work when converted to VectorDrawables, then it makes sense to just use those.

You would only need to consider AndroidSVG if your SVGs are more complex.

> Thanks in advance for all your support.

You're welcome. My pleasure.

**Comment by carlos-mg89** [comment]
Alright, this makes lot of sense as I presumed. Thanks again!
