### ISSUE TITLE
Invalid Layer Save Flag - only ALL_SAVE_FLAGS is allowed

### ISSUE THREAD

**Issue by n1try** [BigBadaboom/androidsvg#148]
I am getting the exception below occasionally when trying to execute the following code with `compileSdkVersion 28` and Java 7. I am using `com.caverock:androidsvg:1.2.1`.

```java
GlideApp.with(context)
                .as(PictureDrawable.class)
                .listener(new SvgSoftwareLayerSetter())
                .load("http://example.com/foo.svg")
                .into(target);
```

```java
public class SvgDrawableTranscoder implements ResourceTranscoder<SVG, PictureDrawable> {
    @Nullable
    @Override
    public Resource<PictureDrawable> transcode(@NonNull Resource<SVG> toTranscode,
                                               @NonNull Options options) {
        SVG svg = toTranscode.get();
        Picture picture = svg.renderToPicture();
        PictureDrawable drawable = new PictureDrawable(picture);
        return new SimpleResource<>(drawable);
    }
}
```

```java
public class SvgDecoder implements ResourceDecoder<InputStream, SVG> {

    @Override
    public boolean handles(@NonNull InputStream source, @NonNull Options options) {
        return true;
    }

    public Resource<SVG> decode(@NonNull InputStream source, int width, int height,
                                @NonNull Options options)
            throws IOException {
        try {
            SVG svg = SVG.getFromInputStream(source);
            return new SimpleResource<>(svg);
        } catch (SVGParseException ex) {
            throw new IOException("Cannot load SVG from stream", ex);
        }
    }
}

```

```java
@GlideModule
public class SvgModule extends AppGlideModule {
    @Override
    public void registerComponents(@NonNull Context context, @NonNull Glide glide,
                                   @NonNull Registry registry) {
        registry.register(SVG.class, PictureDrawable.class, new SvgDrawableTranscoder())
                .append(InputStream.class, SVG.class, new SvgDecoder());
    }

    // Disable manifest parsing to avoid adding similar modules twice.
    @Override
    public boolean isManifestParsingEnabled() {
        return false;
    }
}
```

**Exception:**
```
07-12 22:20:14.474 10798-10847/com.example.n1try.myapp E/GlideExecutor: Request threw uncaught throwable
    java.lang.IllegalArgumentException: Invalid Layer Save Flag - only ALL_SAVE_FLAGS is allowed
        at android.graphics.Canvas.checkValidSaveFlags(Canvas.java:378)
        at android.graphics.Canvas.saveLayerAlpha(Canvas.java:555)
        at com.caverock.androidsvg.SVGAndroidRenderer.pushLayer(SVGAndroidRenderer.java:677)
        at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:982)
        at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:298)
        at com.caverock.androidsvg.SVGAndroidRenderer.renderChildren(SVGAndroidRenderer.java:330)
        at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:584)
        at com.caverock.androidsvg.SVGAndroidRenderer.renderDocument(SVGAndroidRenderer.java:267)
        at com.caverock.androidsvg.SVG.renderToPicture(SVG.java:306)
        at com.caverock.androidsvg.SVG.renderToPicture(SVG.java:286)
        at com.example.n1try.myapp.utils.svg.SvgDrawableTranscoder.transcode(SvgDrawableTranscoder.java:26)
        at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:47)
        at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:58)
        at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:43)
        at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:501)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:472)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:458)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:410)
        at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:379)
        at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:95)
        at com.bumptech.glide.load.model.FileLoader$FileFetcher.loadData(FileLoader.java:76)
        at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:75)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:269)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
```

**Comment by devemux86** [comment]
If use Android P and `targetSdkVersion 28`, then must use SNAPSHOT version, see instructions [here](http://bigbadaboom.github.io/androidsvg/release-1.3.html).

**Comment by BigBadaboom** [comment]
AndroidSVG uses the method `Canvas.save(int flags)` to implement clip path support on pre-Kit Kat devices.   It was previously used for all versions of Android, but I created a new implementation for clip paths in v1.3 that uses APIs that are only available since Kit Kat.

In Android 27 they deprecated the `Canvas.save(int flags)` method and most of the flag values.  That was fair enough.  The new versions of Skia (the underlying library that Android uses for 2D graphics), no longer support the version of `save()` that take flags.

Unfortunately, in Android 28, they seem to have taken the additional step of removing that `save()` method entirely.  That means that the library cannot be compiled with compile/targetSdkVersion set to 28.

If this doesn't change, I will either have to:

- stick at SDK 27 and not take advantage of any new features that get added to Android in the future, or
- remove the old code and drop support for pre-Kit Kat devices (around 5% of users still).

**If you want to help get Android to reverse their decision, please take the time to star the following bug ticket.  And maybe add a supporting comment about how it would affect you if they don't.**  Please be polite.

https://issuetracker.google.com/issues/110856542

In the meantime, you can migrate to the upcoming version 1.3 of AndroidSVG.  Instructions on how you can use the snapshot release of 1.3 can be found on [the 1.3 release notes page](http://bigbadaboom.github.io/androidsvg/release-1.3.html) as @devemux86 said.
.

Thanks,
Paul

**Comment by n1try** [comment]
Thank you very much for your detailed answers! I am going to take a look at that bug report and go with 1.3 snapshot in the meantime :+1:

**Comment by BigBadaboom** [comment]
Google refused to reverse their decision.  So I am going to have to find a way to rewrite the clipPath code, so that it supports older versions of Android **and** compiles on SDK 28+.

I might as well use this bug report for that work, so I am reopening it.

**Comment by BigBadaboom** [comment]
If you don't care about supporting pre-KitKat devices. You can use [this patch](https://github.com/BigBadaboom/androidsvg/pull/144) from @amandeepg in the meantime.

**Comment by MarcBernstein** [comment]
FWIW, the Lottie lib took this approach to resolve the issue: https://github.com/airbnb/lottie-android/pull/748

Seems like it would work fine here as well, no?

**Comment by MarcBernstein** [comment]
Ah, apologies for not noticing that difference.

**Comment by BigBadaboom** [comment]
Thanks to a patch from @brudaswen, this issue is now resolved.

**Comment by knordbo** [comment]
Glad to see a fix for this issue. When can we expect a release with the fix?

**Comment by BigBadaboom** [comment]
@knordbo The problem this fixes only applied to compiling the library itself.

You shouldn't need a new release to build your app with the targetSdkVersion/compileSdkVersion set to 28.  Your app should compile okay with AndroidSVG 1.3.

**Comment by knordbo** [comment]
@BigBadaboom Cheers! Will try out 1.3

**Comment by folecr** [comment]
I blanket ignored proguard errors because of this
```-dontwarn com.caverock.androidsvg.** ```

**Comment by guy7373** [comment]
I am using version 1.3 with Android 28 and still get this error.
In the code I see `canvas.save(Canvas.MATRIX_SAVE_FLAG);`(line 3930)

**Comment by BigBadaboom** [comment]
@guy7373 You must be looking at the wrong code. That line does not appear in the 1.3 version of SVGAndroidRenderer.java.

https://github.com/BigBadaboom/androidsvg/blob/master/androidsvg/src/main/java/com/caverock/androidsvg/SVGAndroidRenderer.java

If you have cloned your own copy of the source, then please check that you have the correct branch and revision.

**Comment by BigBadaboom** [comment]
@guy7373 Sorry. My confusion. The fix for that issue is not in 1.3.  It will be in the next release.  If you need that fix right now, you'll need to clone and build your own.

**Comment by guy7373** [comment]
@BigBadaboom not urgent, thanks
will the next versions be deployed to jcenter?

**Comment by BigBadaboom** [comment]
@guy7373 The versions on Maven Central and jcenter appear to be the same AFAICT.  I only publish to Sonatype, and then they push it to Maven Central.  I am not sure whether jcenter gets it from there, or if Sonatype push it to jcenter also.

**Comment by guy7373** [comment]
@BigBadaboom great!! thank you :)
