### ISSUE TITLE
ArrayOutOfBoundException

### ISSUE THREAD

**Issue by ReIaxo** [BigBadaboom/androidsvg#158]
While using SVG.getFromString() with the string down below, the following exception is thrown:

`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024"><path d="M386.676 491.469c22.088-.329 52.862-3.215 65.802 6.313 9.016 6.627 10.501 21.444 6.825 34.698-1.864 6.89-4.763 14.752-9.066 20.471-7.798 10.303-22.533 15.396-34.847 17.324-3.857.579-45.972.265-46.039.643a26786.804 26786.804 0 0 0 17.324-79.45zm635.969 37.466c-10.484-78.099-85.188-109.136-149.374-134.175-47.259-18.413-100.451-26.786-156.791-37.352l-63.676-5.786c-15.066-.71-30.133-1.418-45.264-2.127h-55.253c-9.264.181-18.543.312-27.873.577l-68.902 5.719c-33.164 6.001-65.934 8.951-96.84 16.879-53.243 13.583-99.215 31.747-142.549 53.704 10.17-21.132 20.34-42.182 30.51-63.165 7.335-13.005 14.752-25.962 22.088-38.967-8.306 5.424-14.159 19.253-19.961 27.38-21.444 30-42.824 60-64.186 89.95-.198.314-.331.71-.594 1.022a47695.491 47695.491 0 0 1-30.445-103.088c-4.384-16.797-8.818-33.676-13.203-50.473 7.533 50.275 19.516 104.439 20.538 158.834-9.66-4.565-19.319-9.066-28.977-13.648-19.632-9.972-38.82-19.632-57.298-30.51a15563.974 15563.974 0 0 1-38.373-22.6c-.594-.198-1.106-.396-1.616-.592l33.099 24.724a48088.576 48088.576 0 0 0 46.863 36.84c11.01 9.016 22.088 17.901 33.099 26.853-11.523 3.659-23.11 7.4-34.698 11.076-36.956 11.39-73.994 22.781-111.017 34.188l-1.022.51c48.94-5.407 97.039-21.115 152.028-21.576v.592c-21.84 44.556-40.632 89.424-64.715 131.473v.51h.579a72733.328 72733.328 0 0 0 48.362-70.501c11.192-15.379 22.468-30.839 33.661-46.302l2.127-1.533c15.065 32.77 22.482 73.006 32.654 109.45 3.478 14.358 7.021 28.732 10.499 43.155v.956h.51c-2.966-19.384-5.934-38.885-8.95-58.402-2.458-20.093-4.896-40.301-7.335-60.46-1.418-13.517-2.836-26.967-4.188-40.501 38.243 15.973 71.786 35.357 105.726 55.253-4.055 17.901-8.11 35.802-12.116 53.637v1.599h98.901c30.082 0 60.923 1.104 82.615-7.402 26.984-10.499 42.051-28.713 52.599-55.764 5.868-14.735 12.759-39.016 7.929-59.933-3.676-15.66-13.45-26.407-26.853-32.143-19.763-8.422-49.713-6.825-77.851-6.825H326.084c-7.714 34.78-15.445 69.478-23.175 104.194h-.51c-21.693-14.111-40.897-31.683-61.039-47.324-10.056-7.863-22.665-15.792-30.527-25.83 34.714-11.076 69.477-22.088 104.192-33.166 8.818-2.768 36.05-7.714 41.011-13.136-16.171 5.736-34.517 6.444-52.617 9.989-16.483 2.324-32.966 4.565-49.449 6.823v-.444c11.72-5.868 23.504-11.588 35.29-17.456 24.346-10.501 50.357-19.055 76.814-27.296 125.95-39.281 341.258-53.77 477.71-13.204 59.621 17.77 137.719 42.051 148.927 106.303 3.99 23.06-8.306 40.962-16.879 52.615-24.972 34.384-63.923 56.078-105.197 74.177-58.598 25.615-123.692 39.856-195.743 54.214-26.982 2.951-53.922 7.153-81 8.95-42.172 2.799-49.676 3.983-86.009 3.589l-30.805-.79c-23.709-1.304-41.073-1.975-68.717-5.924-39.501-5.644-76.721-12.802-111.37-23.697-19.896-6.231-47.787-16.191-68.768-20.5-8.97-1.841 17.391 8.687 26.341 12.544 25.945 11.274 52.929 19.647 82.533 28.465 164.837 49.254 416.671 34.633 556.715-24.724 44.227-18.807 84.859-40.434 111.002-77.324 8.175-11.605 20.736-30.923 17.835-52.105zm-223.039-79.448a646225.813 646225.813 0 0 1-36.313 162h68.374c12.116-53.951 24.214-107.984 36.313-162h-68.374zm-106.302 98.901c-8.637 22.796-76.368 31.993-82.104 1.087-5.077-27.873 17.324-51.889 36.84-56.851 22.204-5.605 52.533-2.309 50.028 21.065h77.324c.906-42.511-18.412-55.516-54.147-62.143 0 0-67.418-3.857-89.44-.263-48.48 8.059-75.645 27.559-88.979 71.356-3.099 10.237-7.533 24.841-5.226 39.397 7.6 47.785 51 49.451 106.254 49.451 24.856 0 49.698.263 68.951-5.721 27.247-8.571 44.307-31.812 54.741-57.378h-74.242z"/></svg>`

```
java.lang.ArrayIndexOutOfBoundsException: length=0; index=-2
        at com.caverock.androidsvg.SVGAndroidRenderer.arcTo(SVGAndroidRenderer.java:2699)
        at com.caverock.androidsvg.SVGAndroidRenderer.access$700(SVGAndroidRenderer.java:90)
        at com.caverock.androidsvg.SVGAndroidRenderer$PathConverter.arcTo(SVGAndroidRenderer.java:2561)
        at com.caverock.androidsvg.SVG$PathDefinition.enumeratePath(SVG.java:2303)
        at com.caverock.androidsvg.SVGAndroidRenderer$PathConverter.<init>(SVGAndroidRenderer.java:2518)
        at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:1065)
        at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:343)
        at com.caverock.androidsvg.SVGAndroidRenderer.renderChildren(SVGAndroidRenderer.java:375)
        at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:621)
        at com.caverock.androidsvg.SVGAndroidRenderer.renderDocument(SVGAndroidRenderer.java:308)
        at com.caverock.androidsvg.SVG.renderToPicture(SVG.java:436)
        at com.caverock.androidsvg.SVG.renderToPicture(SVG.java:409)
        at com.caverock.androidsvg.SVGImageView.doRender(SVGImageView.java:355)
        at com.caverock.androidsvg.SVGImageView.setSVG(SVGImageView.java:142)
```

Hope you can fix it. If you need more information, i can reproduce it.

**Comment by BigBadaboom** [comment]
Thanks for your report.  This is probably a duplicate of #155.  I will take a look and confirm shortly.

**Comment by ReIaxo** [comment]
No I do not work with @hellaandrew, but this is the symbol of a expansion of the collectible card game Magic the Gathering. It is the only image from hundrets which won't work.

This time span is ok for me, it is not a critical issue for me.

Good luck with you library in future.

**Comment by hellaandrew** [comment]
@ReIaxo I think we provided @BigBadaboom with the same vector image haha

**Comment by nilsi** [comment]
Also seeing this exact issue running android 4.4
