### ISSUE TITLE
IllegalArgumentException bad base-64

### ISSUE THREAD

**Issue by mueller-ma** [BigBadaboom/androidsvg#170]
Hey,
I see the following crash in your lib (Version 3511e136498da94018ef9fa438895984ea9b99db):

````java
Fatal Exception: java.lang.IllegalArgumentException: bad base-64
       at android.util.Base64.decode(Base64.java:161)
       at android.util.Base64.decode(Base64.java:136)
       at android.util.Base64.decode(Base64.java:118)
       at com.caverock.androidsvg.SVGAndroidRenderer.checkForImageDataURL(SVGAndroidRenderer.java:1939)
       at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:1860)
       at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:300)
       at com.caverock.androidsvg.SVGAndroidRenderer.renderChildren(SVGAndroidRenderer.java:334)
       at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:623)
       at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:298)
       at com.caverock.androidsvg.SVGAndroidRenderer.renderChildren(SVGAndroidRenderer.java:334)
       at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:580)
       at com.caverock.androidsvg.SVGAndroidRenderer.renderDocument(SVGAndroidRenderer.java:268)
       at com.caverock.androidsvg.SVG.renderToCanvas(SVG.java:466)
       at com.caverock.androidsvg.SVG.renderToCanvas(SVG.java:443)
       at org.openhab.habdroid.util.AsyncHttpClient$BitmapResponseHandler.getBitmapFromSvgInputstream(AsyncHttpClient.java:126)
````

https://github.com/openhab/openhab-android/blob/master/mobile/src/main/java/org/openhab/habdroid/util/AsyncHttpClient.java#L126

**Comment by BigBadaboom** [comment]
Hi. Thanks for the report.

What can you tell me about the SVG?  Does it work in a browser?  If it does, can you attach it or send it to me please?

**Comment by mueller-ma** [comment]
The svg is defined by the end-user and the crash occurs only for one user. He didn't contact me so far, so I don't have access to the svg.
For now I suggest to catch the IllegalArgumentException and re-throw it as SVGParseException. And if I get this svg, I can post it here.

**Comment by mueller-ma** [comment]
Thanks!

**Comment by mueller-ma** [comment]
Hey @BigBadaboom,
can you tag a new release so I can use this fix?

**Comment by BigBadaboom** [comment]
Working on it. Sonatype not behaving at the moment tho. Stay tuned.

**Comment by BigBadaboom** [comment]
Sonatype is back up. The 1.4 release should be available from the Maven Central repo soon.

**Comment by mueller-ma** [comment]
Thanks. Maybe you want to set up jitpack.io, so people can use snapshots: https://jitpack.io/docs/#publishing-on-jitpack

**Comment by mueller-ma** [comment]
Actually it did work with jitpack.io: https://github.com/openhab/openhab-android/blob/master/mobile/build.gradle#L110
