### ISSUE TITLE
 java.lang.ArrayIndexOutOfBoundsException: length=0; index=-2 v 1.4

### ISSUE THREAD

**Issue by KravaDanil** [BigBadaboom/androidsvg#176]
I think bug is stil reproducible in v 1.4 
Encountered this today: 
`java.lang.ArrayIndexOutOfBoundsException: length=0; index=-2
        at com.caverock.androidsvg.SVGAndroidRenderer.arcTo(SVGAndroidRenderer.java:2730)
        at com.caverock.androidsvg.SVGAndroidRenderer.access$700(SVGAndroidRenderer.java:89)
        at com.caverock.androidsvg.SVGAndroidRenderer$PathConverter.arcTo(SVGAndroidRenderer.java:2584)
        at com.caverock.androidsvg.SVG$PathDefinition.enumeratePath(SVG.java:2311)
        at com.caverock.androidsvg.SVGAndroidRenderer$PathConverter.<init>(SVGAndroidRenderer.java:2541)
        at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:1082)
        at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:348)
        at com.caverock.androidsvg.SVGAndroidRenderer.renderChildren(SVGAndroidRenderer.java:380)
        at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:668)
        at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:344)
        at com.caverock.androidsvg.SVGAndroidRenderer.renderChildren(SVGAndroidRenderer.java:380)
        at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:625)
        at com.caverock.androidsvg.SVGAndroidRenderer.renderDocument(SVGAndroidRenderer.java:313)
        at com.caverock.androidsvg.SVG.renderToCanvas(SVG.java:540)
        at com.caverock.androidsvg.SVG.renderToCanvas(SVG.java:494)`

SVG file: 
[f06a2b6b-ab23-4d12-abc6-e4a0cb4f30c3.zip](https://github.com/BigBadaboom/androidsvg/files/3383903/f06a2b6b-ab23-4d12-abc6-e4a0cb4f30c3.zip)

**Comment by BigBadaboom** [comment]
Thanks for the report.  I have reopened bug #155.  So I'll mark this a dup of that one.

**Comment by BigBadaboom** [comment]
Turns out this is a slightly different issue to #155, with the same symptoms. So makes sense to reopen and apply the fix under the auspices of this bug ticket.

**Comment by BigBadaboom** [comment]
Fixed.

This change will be in the next (1.5) release.

**Comment by KravaDanil** [comment]
Thank you for fix!

**Comment by cbukenya** [comment]
How can we get this fix, seems last release is still on 1.4

**Comment by BigBadaboom** [comment]
I still have a few [fixes to complete for release 1.5](https://github.com/BigBadaboom/androidsvg/milestone/5).

In the meantime, you could download and build yourself. It should be quite straightforward.
