### ISSUE TITLE
Can't include your library into my android project

### ISSUE THREAD

**Issue by ednjv** [BigBadaboom/androidsvg#76]
I'm using the following xml file example

<com.caverock.androidsvg.SVGImageView
        android:id="@+id/imageView1"
        android:layout_width="100dp"
        android:layout_height="100dp"
        svgimageview:svg="@drawable/asd" />

when I try to build the project I get the next error:

Error:(16) No resource identifier found for attribute 'svg' in package 'com.company.project'

I'm really new to the Android enviroment, can you help me please?

**Comment by BigBadaboom** [comment]
Hi. Sorry for the slow reply.

Try copying the `attrs.xml` file from here:

https://github.com/BigBadaboom/androidsvg/tree/master/res/values

into your res/values folder.  It should build then.

**Comment by ednjv** [comment]
Omg ty now i can build the project but he's crashing with this exception:

     android.view.InflateException: Binary XML file line #27: Error inflating class android.support.design.widget.NavigationView

**Comment by BigBadaboom** [comment]
Please add more information.  What is line #27 in your layout file?  Can you include the relevant bit of the file.  If it isn't related to `SVGImageView` then it is probably not AndroidSVG related.

**Comment by ednjv** [comment]
**When i commented the AndroidSVG tag my app run ok **. i gonna paste my full log here.

``` 11-02 08:51:33.414 23882-23882/com.metamax.tumatadero E/dalvikvm: Could not find class 'android.app.AppOpsManager', referenced from method com.google.android.gms.common.GooglePlayServicesUtil.zzb
11-02 08:51:33.562 23882-23964/com.metamax.tumatadero E/GMPM: getGoogleAppId failed with status: 10
11-02 08:51:33.562 23882-23964/com.metamax.tumatadero E/GMPM: Uploading is not possible. App measurement disabled
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime: FATAL EXCEPTION: main
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.metamax.tumatadero/com.metamax.tumatadero.actividades.ActividadPrincipal}: android.view.InflateException: Binary XML file line #27: Error inflating class android.support.design.widget.NavigationView
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2262)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2316)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.ActivityThread.access$700(ActivityThread.java:158)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1296)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:176)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5365)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:  Caused by: android.view.InflateException: Binary XML file line #27: Error inflating class android.support.design.widget.NavigationView
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.createView(LayoutInflater.java:619)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:257)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at com.metamax.tumatadero.actividades.ActividadPrincipal.onCreate(ActividadPrincipal.java:26)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:5326)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2225)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2316) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.ActivityThread.access$700(ActivityThread.java:158) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1296) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:176) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5365) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:  Caused by: java.lang.reflect.InvocationTargetException
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at java.lang.reflect.Constructor.constructNative(Native Method)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.createView(LayoutInflater.java:593)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:752) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:257) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at com.metamax.tumatadero.actividades.ActividadPrincipal.onCreate(ActividadPrincipal.java:26) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:5326) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2225) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2316) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.ActivityThread.access$700(ActivityThread.java:158) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1296) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:176) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5365) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:  Caused by: android.view.InflateException: Binary XML file line #16: Error inflating class com.caverock.androidsvg.SVGImageView
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.createView(LayoutInflater.java:619)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.support.design.internal.NavigationMenuPresenter.inflateHeaderView(NavigationMenuPresenter.java:190)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.support.design.widget.NavigationView.inflateHeaderView(NavigationView.java:250)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.support.design.widget.NavigationView.<init>(NavigationView.java:172)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.support.design.widget.NavigationView.<init>(NavigationView.java:94)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at java.lang.reflect.Constructor.constructNative(Native Method) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.createView(LayoutInflater.java:593) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:752) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:257) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at com.metamax.tumatadero.actividades.ActividadPrincipal.onCreate(ActividadPrincipal.java:26) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:5326) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2225) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2316) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.ActivityThread.access$700(ActivityThread.java:158) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1296) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:176) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5365) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:  Caused by: java.lang.reflect.InvocationTargetException
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at java.lang.reflect.Constructor.constructNative(Native Method)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.createView(LayoutInflater.java:593)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:752) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.support.design.internal.NavigationMenuPresenter.inflateHeaderView(NavigationMenuPresenter.java:190) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.support.design.widget.NavigationView.inflateHeaderView(NavigationView.java:250) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.support.design.widget.NavigationView.<init>(NavigationView.java:172) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.support.design.widget.NavigationView.<init>(NavigationView.java:94) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at java.lang.reflect.Constructor.constructNative(Native Method) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.createView(LayoutInflater.java:593) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:752) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:257) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at com.metamax.tumatadero.actividades.ActividadPrincipal.onCreate(ActividadPrincipal.java:26) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:5326) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2225) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2316) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.ActivityThread.access$700(ActivityThread.java:158) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1296) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:176) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5365) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:  Caused by: java.lang.NoClassDefFoundError: com.caverock.androidsvg.R$styleable
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at com.caverock.androidsvg.SVGImageView.init(SVGImageView.java:80)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at com.caverock.androidsvg.SVGImageView.<init>(SVGImageView.java:66)
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at java.lang.reflect.Constructor.constructNative(Native Method) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.createView(LayoutInflater.java:593) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:752) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.support.design.internal.NavigationMenuPresenter.inflateHeaderView(NavigationMenuPresenter.java:190) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.support.design.widget.NavigationView.inflateHeaderView(NavigationView.java:250) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.support.design.widget.NavigationView.<init>(NavigationView.java:172) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.support.design.widget.NavigationView.<init>(NavigationView.java:94) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at java.lang.reflect.Constructor.constructNative(Native Method) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.createView(LayoutInflater.java:593) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:752) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:257) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at com.metamax.tumatadero.actividades.ActividadPrincipal.onCreate(ActividadPrincipal.java:26) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:5326) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2225) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2316) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.ActivityThread.access$700(ActivityThread.java:158) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1296) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:176) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5365) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869) 
11-02 08:51:34.000 23882-23882/com.metamax.tumatadero E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)  ```


here is the file where i try put de svg image:

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"

    xmlns:svgimageview="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent" android:layout_height="@dimen/nav_header_height"
    android:background="@color/colorPrimary"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    android:theme="@style/ThemeOverlay.AppCompat.Dark" android:orientation="vertical"
    android:gravity="bottom"
    android:weightSum="1">

    <com.caverock.androidsvg.SVGImageView
        android:id="@+id/imageView1"
        android:layout_width="100dp"
        android:layout_height="100dp"
        svgimageview:svg="@drawable/matadero" />



    <TextView android:layout_width="match_parent" android:layout_height="wrap_content"
        android:paddingTop="10dp" android:text="Android Studio"
        android:textAppearance="@style/TextAppearance.AppCompat.Body1" />

    <TextView android:layout_width="wrap_content" android:layout_height="wrap_content"
        android:text="android.studio@android.com" android:id="@+id/textView" />

</LinearLayout>


**i'm trying to find  that line, My sSVG file is imported by android studio. this way New -> Vector Assets **

**Comment by caoyunxuan07** [comment]
"Oh!Young skywalker, 404 this is not the web page you looking for."

**Comment by BigBadaboom** [comment]
Updated link to attrs.xml file:

https://github.com/BigBadaboom/androidsvg/blob/master/androidsvg/src/main/res/values/attrs.xml
