### ISSUE TITLE
Parse failure (file included)

### ISSUE THREAD

**Issue by mstevens83** [BigBadaboom/androidsvg#81]
I noticed the SVG parser crashes when trying to load this SVG file:
http://soft.vub.ac.be/~mstevens/tmp/crashing_svg.zip

Here's the relevant part of the stacktrace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.StringBuilder.toString()' on a null object reference
	at com.caverock.androidsvg.SVGParser.endElement(SVGParser.java:596)
	at org.apache.harmony.xml.ExpatParser.endElement(ExpatParser.java:156)
	at org.apache.harmony.xml.ExpatParser.appendBytes(Native Method)
	at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:513)
	at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:474)
	at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:316)
	at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:279)
	at com.caverock.androidsvg.SVGParser.parse(SVGParser.java:394)
	at com.caverock.androidsvg.SVG.getFromResource(SVG.java:187)
```

**Comment by BigBadaboom** [comment]
Added sample file as ZIP

[Issue81.zip](https://github.com/BigBadaboom/androidsvg/files/92787/Issue81.zip)

**Comment by BigBadaboom** [comment]
Fixed.

The problem was caused by empty metadata elements. For example: `<title/>` and `<desc/>`.  As a workaround, you can get this file to render correctly by removing those elements.

**Comment by mstevens83** [comment]
Cool, thanks!
